stages:
  preprocess:
    cmd: python3 scripts/preprocess.py -v
    params:
      - preprocess.size
      - preprocess.overwrite
  encode:
    cmd: python3 scripts/classification/encode.py -v
    params:
      - encode.backbone
      - encode.overwrite
      - encode.batch

