artifact_uri: file:///home/salemi/Documents/Kaggle/happywhale/mlflow/0/70c3ecbe01fe487fb659b3897a481423/artifacts
end_time: 1644105125250
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 70c3ecbe01fe487fb659b3897a481423
run_uuid: 70c3ecbe01fe487fb659b3897a481423
source_name: ''
source_type: 4
source_version: ''
start_time: 1644105120217
status: 3
tags: []
user_id: salemi
