artifact_uri: file:///home/salemi/Documents/Kaggle/happywhale/mlflow/1/18c0acfb9ab944dbaa1adf9e17e9cc51/artifacts
end_time: 1644106076358
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 18c0acfb9ab944dbaa1adf9e17e9cc51
run_uuid: 18c0acfb9ab944dbaa1adf9e17e9cc51
source_name: ''
source_type: 4
source_version: ''
start_time: 1644105832611
status: 3
tags: []
user_id: salemi
