BATCH_SIZE: 32
CUTOFF: 19
EPOCHS: 25
LEARNING_RATE: 0.001
LEARNING_RATE_FINETUNING: 5.0e-05
STEPS_PER_EPOCH: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AAAAAAAAQ0A=
TEST_RUN: true
TRAIN_CSV: input/happy-whale-and-dolphin/train.csv
TRAIN_FOLDER: input/happy-whale-and-dolphin/train_images
